name: build-windows-2022

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/build_windows_2022.yaml"

jobs:
  build-windows:
    runs-on: windows-2022
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      - name: Enable Flutter Desktop
        run: flutter config --enable-windows-desktop

      - name: Restore packages
        run: |
          cd simple_live_app
          flutter pub get

      - name: Build Windows
        run: |
          cd simple_live_app
          flutter build windows --release

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: simple_live_app/build/windows/x64/runner/Release/**
